### ISSUE TITLE
Add ability to list files in a zipfile

### ISSUE THREAD

**Issue by empavia** [natcap/geometamaker#40]
Our UI/UX contract team has requested the ability to list out files in a zipfile in the metadata file. The catalog will be listing files to be found in a zipfile and the metadata can facilitate that while acting as a source of truth. It would be great to list the paths similar to how text files list fields.

**Comment by jagoldstein** [comment]
I agree that this feature would be very useful, because otherwise there's the risk of dataset creators only providing metadata for the zip generally, rather than there being metadata to describe each file within it. We battled this issue at NCEAS when researchers wanted to cut corners by only describing the top-level zip (or other compressed format) file, but of course having only that coarse level of detail is usually insufficient for other users.

**Comment by davemfish** [comment]
> I agree that this feature would be very useful, because otherwise there's the risk of dataset creators only providing metadata for the zip generally, rather than there being metadata to describe each file within it. We battled this issue at NCEAS when researchers wanted to cut corners by only describing the top-level zip (or other compressed format) file, but of course having only that coarse level of detail is usually insufficient for other users.

That's good to hear about your experiences, @jagoldstein . I think in the simplest form, this issue is about listing out the filepaths of all the files contained within the zip. Similar to how all the component files of a shapefile will get listed in the `sources` section of the metadata for a shapefile.

I agree it will be very useful to encourage users to create metadata for all the files within a zip, and I think that metadata should exist as a `yml` sidecar file for each of the individual files. We've talked about a feature to check for metadata "coverage" for all the files in a directory. That could be extended to check all files in a zip.
