### ISSUE TITLE
Different keyword categories

### ISSUE THREAD

**Issue by empavia** [natcap/geometamaker#47]
Stamen (our UI/UX contractors) have requested that we look into splitting the keywords for locations and other items. For example, have a subset of keywords to represent "place" (global, country names, etc.) vs standard keywords for everything else. It appears there is not an easy way to do this by modifying lists in set_keywords(). I believe this would be similar to keyword themes in the MCF and other metadata formats.

**Comment by empavia** [comment]
I like the idea of creating another section to hold placenames.

Right now the process is just up to the discretion of the metadata creator. However, I will be reviewing keywords and placenames before uploading data to the catalog. Not sure how `geometamaker` can help with it directly, unless you have a particular idea?

**Comment by davemfish** [comment]
> I like the idea of creating another section to hold placenames.
> 
> Right now the process is just up to the discretion of the metadata creator. However, I will be reviewing keywords and placenames before uploading data to the catalog. Not sure how `geometamaker` can help with it directly, unless you have a particular idea?

Cool. I don't have any great ideas. Something like reverse-geocoding comes to mind. Since we know the location of the data, we could lookup some placenames associated with it. But that gets very complicated since we're dealing with areas and not simple points. So it's probably best for a human to add the placenames.
